#include "TestReportGenerator.h"
#include <QStandardPaths>
#include <QTextStream>
#include <QJsonArray>
#include <QDebug>
#include <QProcess>
#include <QOperatingSystemVersion>
#include <QSysInfo>

namespace Glance::Testing {

// HTML and CSS templates
const QString TestReportGenerator::HTML_TEMPLATE = R"(
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{TITLE}</title>
    <style>
        {CSS_STYLES}
    </style>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <div class="container">
        <header>
            <h1>{TITLE}</h1>
            <div class="timestamp">Generated: {TIMESTAMP}</div>
        </header>
        
        <nav>
            <ul>
                <li><a href="#summary">Summary</a></li>
                <li><a href="#test-results">Test Results</a></li>
                <li><a href="#benchmarks">Benchmarks</a></li>
                <li><a href="#charts">Charts</a></li>
                <li><a href="#analysis">Analysis</a></li>
            </ul>
        </nav>
        
        <main>
            <section id="summary">
                {SUMMARY_SECTION}
            </section>
            
            <section id="test-results">
                {TEST_RESULTS_SECTION}
            </section>
            
            <section id="benchmarks">
                {BENCHMARK_RESULTS_SECTION}
            </section>
            
            <section id="charts">
                {CHARTS_SECTION}
            </section>
            
            <section id="analysis">
                {ANALYSIS_SECTION}
            </section>
        </main>
        
        <footer>
            <p>Generated by Glance Test Report Generator</p>
        </footer>
    </div>
    
    <script>
        {JAVASCRIPT_CHARTS}
    </script>
</body>
</html>
)";

const QString TestReportGenerator::CSS_STYLES = R"(
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    line-height: 1.6;
    color: #333;
    background-color: #f5f5f5;
}

.container {
    max-width: 1200px;
    margin: 0 auto;
    background-color: white;
    box-shadow: 0 0 10px rgba(0,0,0,0.1);
}

header {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    padding: 2rem;
    text-align: center;
}

header h1 {
    font-size: 2.5rem;
    margin-bottom: 0.5rem;
}

.timestamp {
    font-size: 0.9rem;
    opacity: 0.8;
}

nav {
    background-color: #2c3e50;
    padding: 0;
}

nav ul {
    list-style: none;
    display: flex;
    justify-content: center;
}

nav li {
    margin: 0;
}

nav a {
    display: block;
    color: white;
    text-decoration: none;
    padding: 1rem 2rem;
    transition: background-color 0.3s;
}

nav a:hover {
    background-color: #34495e;
}

main {
    padding: 2rem;
}

section {
    margin-bottom: 3rem;
}

section h2 {
    color: #2c3e50;
    border-bottom: 2px solid #3498db;
    padding-bottom: 0.5rem;
    margin-bottom: 1.5rem;
}

.summary-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 1rem;
    margin-bottom: 2rem;
}

.summary-card {
    background: white;
    border-radius: 8px;
    padding: 1.5rem;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    text-align: center;
}

.summary-card h3 {
    color: #7f8c8d;
    font-size: 0.9rem;
    margin-bottom: 0.5rem;
}

.summary-card .value {
    font-size: 2rem;
    font-weight: bold;
    color: #2c3e50;
}

.success { color: #27ae60; }
.failure { color: #e74c3c; }
.warning { color: #f39c12; }
.info { color: #3498db; }

.test-table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 1rem;
}

.test-table th,
.test-table td {
    padding: 0.75rem;
    text-align: left;
    border-bottom: 1px solid #ddd;
}

.test-table th {
    background-color: #f8f9fa;
    font-weight: 600;
}

.test-table tr:hover {
    background-color: #f8f9fa;
}

.status-passed {
    background-color: #d4edda;
    color: #155724;
}

.status-failed {
    background-color: #f8d7da;
    color: #721c24;
}

.status-skipped {
    background-color: #fff3cd;
    color: #856404;
}

.chart-container {
    position: relative;
    height: 400px;
    margin: 2rem 0;
}

.benchmark-table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 1rem;
}

.benchmark-table th,
.benchmark-table td {
    padding: 0.75rem;
    text-align: left;
    border-bottom: 1px solid #ddd;
}

.benchmark-table th {
    background-color: #e8f4f8;
    font-weight: 600;
}

.analysis-section {
    background-color: #f8f9fa;
    padding: 1.5rem;
    border-radius: 8px;
    margin-top: 1rem;
}

.regression-item {
    background-color: #fff5f5;
    border-left: 4px solid #e53e3e;
    padding: 1rem;
    margin: 0.5rem 0;
}

.improvement-item {
    background-color: #f0fff4;
    border-left: 4px solid #38a169;
    padding: 1rem;
    margin: 0.5rem 0;
}

footer {
    background-color: #2c3e50;
    color: white;
    text-align: center;
    padding: 1rem;
    margin-top: 2rem;
}

@media (max-width: 768px) {
    .container {
        margin: 0;
    }
    
    nav ul {
        flex-direction: column;
    }
    
    .summary-grid {
        grid-template-columns: 1fr;
    }
    
    .test-table {
        font-size: 0.8rem;
    }
}

@media print {
    nav {
        display: none;
    }
    
    .container {
        box-shadow: none;
    }
}
)";

const QString TestReportGenerator::JAVASCRIPT_CHARTS = R"(
// Chart.js configurations
document.addEventListener('DOMContentLoaded', function() {
    // Test Results Pie Chart
    const testResultsCtx = document.getElementById('testResultsChart');
    if (testResultsCtx) {
        new Chart(testResultsCtx, {
            type: 'pie',
            data: {
                labels: ['Passed', 'Failed', 'Skipped'],
                datasets: [{
                    data: [{PASSED_COUNT}, {FAILED_COUNT}, {SKIPPED_COUNT}],
                    backgroundColor: ['#27ae60', '#e74c3c', '#f39c12'],
                    borderWidth: 2
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: {
                        position: 'bottom'
                    },
                    title: {
                        display: true,
                        text: 'Test Results Distribution'
                    }
                }
            }
        });
    }
    
    // Performance Trend Chart
    const performanceCtx = document.getElementById('performanceChart');
    if (performanceCtx) {
        new Chart(performanceCtx, {
            type: 'line',
            data: {
                labels: {PERFORMANCE_LABELS},
                datasets: [{
                    label: 'Performance (ms)',
                    data: {PERFORMANCE_DATA},
                    borderColor: '#3498db',
                    backgroundColor: 'rgba(52, 152, 219, 0.1)',
                    tension: 0.4
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    title: {
                        display: true,
                        text: 'Performance Trend'
                    }
                },
                scales: {
                    y: {
                        beginAtZero: true,
                        title: {
                            display: true,
                            text: 'Time (ms)'
                        }
                    },
                    x: {
                        title: {
                            display: true,
                            text: 'Test'
                        }
                    }
                }
            }
        });
    }
    
    // Benchmark Comparison Chart
    const benchmarkCtx = document.getElementById('benchmarkChart');
    if (benchmarkCtx) {
        new Chart(benchmarkCtx, {
            type: 'bar',
            data: {
                labels: {BENCHMARK_LABELS},
                datasets: [{
                    label: 'Current',
                    data: {BENCHMARK_CURRENT_DATA},
                    backgroundColor: '#3498db'
                }, {
                    label: 'Baseline',
                    data: {BENCHMARK_BASELINE_DATA},
                    backgroundColor: '#95a5a6'
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    title: {
                        display: true,
                        text: 'Benchmark Comparison'
                    }
                },
                scales: {
                    y: {
                        beginAtZero: true,
                        title: {
                            display: true,
                            text: 'Value'
                        }
                    }
                }
            }
        });
    }
});

// Interactive table sorting
function sortTable(tableId, column) {
    const table = document.getElementById(tableId);
    const tbody = table.querySelector('tbody');
    const rows = Array.from(tbody.querySelectorAll('tr'));
    
    rows.sort((a, b) => {
        const aText = a.cells[column].textContent.trim();
        const bText = b.cells[column].textContent.trim();
        
        // Try to parse as number
        const aNum = parseFloat(aText);
        const bNum = parseFloat(bText);
        
        if (!isNaN(aNum) && !isNaN(bNum)) {
            return aNum - bNum;
        }
        
        return aText.localeCompare(bText);
    });
    
    rows.forEach(row => tbody.appendChild(row));
}

// Expandable test details
function toggleTestDetails(testId) {
    const details = document.getElementById('details-' + testId);
    if (details) {
        details.style.display = details.style.display === 'none' ? 'block' : 'none';
    }
}
)";

TestReportGenerator::TestReportGenerator(QObject *parent)
    : QObject(parent)
{
    // Set default output directory
    m_outputDirectory = QStandardPaths::writableLocation(QStandardPaths::DocumentsLocation) + "/GlanceTestReports";
    QDir().mkpath(m_outputDirectory);
    
    m_reportTitle = "Glance Test Report";
    
    // Collect system information
    QJsonObject systemInfo;
    systemInfo["os"] = QSysInfo::prettyProductName();
    systemInfo["kernel"] = QSysInfo::kernelVersion();
    systemInfo["architecture"] = QSysInfo::currentCpuArchitecture();
    systemInfo["hostname"] = QSysInfo::machineHostName();
    systemInfo["qt_version"] = QT_VERSION_STR;
    
    m_environmentInfo = systemInfo;
}

TestReportGenerator::~TestReportGenerator() = default;

void TestReportGenerator::setOutputDirectory(const QString& directory)
{
    m_outputDirectory = directory;
    QDir().mkpath(m_outputDirectory);
}

void TestReportGenerator::setReportTitle(const QString& title)
{
    m_reportTitle = title;
}

void TestReportGenerator::setEnvironmentInfo(const QJsonObject& info)
{
    m_environmentInfo = info;
}

void TestReportGenerator::addTestResult(const TestResult& result)
{
    m_testResults.append(result);
    
    if (m_suiteActive) {
        m_currentSuite.totalTests++;
        if (result.passed) {
            m_currentSuite.passedTests++;
        } else {
            m_currentSuite.failedTests++;
        }
    }
}

void TestReportGenerator::addBenchmarkResult(const TestBenchmarkResult& result)
{
    m_benchmarkResults.append(result);
}

void TestReportGenerator::startTestSuite(const QString& suiteName)
{
    m_currentSuite = TestSuiteSummary();
    m_currentSuite.suiteName = suiteName;
    m_currentSuite.startTime = QDateTime::currentDateTime();
    m_currentSuite.environment = QSysInfo::prettyProductName();
    m_currentSuite.systemInfo = m_environmentInfo;
    
    m_suiteStartTime = QDateTime::currentDateTime();
    m_suiteActive = true;
}

void TestReportGenerator::endTestSuite()
{
    if (m_suiteActive) {
        m_currentSuite.endTime = QDateTime::currentDateTime();
        m_currentSuite.totalDurationMs = m_suiteStartTime.msecsTo(m_currentSuite.endTime);
        m_currentSuite.successRate = calculateSuccessRate();
        
        m_suiteActive = false;
    }
}

bool TestReportGenerator::generateJsonReport()
{
    QJsonObject report;
    report["title"] = m_reportTitle;
    report["generated_at"] = QDateTime::currentDateTime().toString(Qt::ISODate);
    report["environment"] = m_environmentInfo;
    
    // Add test suite summary
    QJsonObject suiteSummary;
    suiteSummary["name"] = m_currentSuite.suiteName;
    suiteSummary["start_time"] = m_currentSuite.startTime.toString(Qt::ISODate);
    suiteSummary["end_time"] = m_currentSuite.endTime.toString(Qt::ISODate);
    suiteSummary["total_tests"] = m_currentSuite.totalTests;
    suiteSummary["passed_tests"] = m_currentSuite.passedTests;
    suiteSummary["failed_tests"] = m_currentSuite.failedTests;
    suiteSummary["skipped_tests"] = m_currentSuite.skippedTests;
    suiteSummary["total_duration_ms"] = m_currentSuite.totalDurationMs;
    suiteSummary["success_rate"] = m_currentSuite.successRate;
    
    report["test_suite"] = suiteSummary;
    
    // Add test results
    QJsonArray testResults;
    for (const auto& result : m_testResults) {
        QJsonObject testResult;
        testResult["name"] = result.testName;
        testResult["category"] = result.category;
        testResult["passed"] = result.passed;
        testResult["duration_ms"] = result.durationMs;
        testResult["timestamp"] = result.timestamp.toString(Qt::ISODate);
        
        if (!result.errorMessage.isEmpty()) {
            testResult["error"] = result.errorMessage;
        }
        
        if (!result.warnings.isEmpty()) {
            QJsonArray warnings;
            for (const QString& warning : result.warnings) {
                warnings.append(warning);
            }
            testResult["warnings"] = warnings;
        }
        
        if (!result.metrics.isEmpty()) {
            testResult["metrics"] = result.metrics;
        }
        
        testResults.append(testResult);
    }
    report["test_results"] = testResults;
    
    // Add benchmark results
    QJsonArray benchmarkResults;
    for (const auto& result : m_benchmarkResults) {
        QJsonObject benchmark;
        benchmark["name"] = result.testName;
        benchmark["value"] = result.value;
        benchmark["unit"] = result.unit;
        benchmark["category"] = result.category;
        benchmark["timestamp"] = result.timestamp.toString(Qt::ISODate);
        
        if (!result.details.isEmpty()) {
            benchmark["details"] = result.details;
        }
        
        benchmarkResults.append(benchmark);
    }
    report["benchmark_results"] = benchmarkResults;
    
    // Add analysis
    report["analysis"] = analyzeTestResults();
    
    // Generate JSON document
    QJsonDocument doc(report);
    QString jsonContent = doc.toJson();
    
    QString filePath = getReportFilePath("json");
    bool success = writeToFile(filePath, jsonContent);
    
    if (success) {
        reportGenerated("JSON", filePath);
    }
    
    return success;
}

bool TestReportGenerator::generateHtmlReport()
{
    QString html = HTML_TEMPLATE;
    
    // Replace placeholders
    html.replace("{TITLE}", m_reportTitle);
    html.replace("{TIMESTAMP}", QDateTime::currentDateTime().toString());
    html.replace("{CSS_STYLES}", CSS_STYLES);
    
    // Generate sections
    html.replace("{SUMMARY_SECTION}", generateHtmlSummary());
    html.replace("{TEST_RESULTS_SECTION}", generateHtmlTestResults());
    html.replace("{BENCHMARK_RESULTS_SECTION}", generateHtmlBenchmarkResults());
    html.replace("{CHARTS_SECTION}", generateHtmlCharts());
    html.replace("{ANALYSIS_SECTION}", generateHtmlAnalysis());
    
    // Generate JavaScript with actual data
    QString js = JAVASCRIPT_CHARTS;
    js.replace("{PASSED_COUNT}", QString::number(m_currentSuite.passedTests));
    js.replace("{FAILED_COUNT}", QString::number(m_currentSuite.failedTests));
    js.replace("{SKIPPED_COUNT}", QString::number(m_currentSuite.skippedTests));
    
    // Add chart data
    QStringList performanceLabels;
    QList<double> performanceData;
    for (const auto& result : m_testResults) {
        performanceLabels << result.testName;
        performanceData << result.durationMs;
    }
    
    js.replace("{PERFORMANCE_LABELS}", QString("[%1]").arg(performanceLabels.join(",")));
    QStringList stringData;
    for (double val : performanceData) {
        stringData << QString::number(val);
    }
    js.replace("{PERFORMANCE_DATA}", QString("[%1]").arg(stringData.join(",")));
    
    html.replace("{JAVASCRIPT_CHARTS}", js);
    
    QString filePath = getReportFilePath("html");
    bool success = writeToFile(filePath, html);
    
    if (success) {
        reportGenerated("HTML", filePath);
    }
    
    return success;
}

bool TestReportGenerator::generateXmlReport()
{
    QString xmlContent;
    QXmlStreamWriter writer(&xmlContent);
    writer.setAutoFormatting(true);
    writer.writeStartDocument();
    
    // Write test suite
    writer.writeStartElement("testsuite");
    writer.writeAttribute("name", m_currentSuite.suiteName);
    writer.writeAttribute("tests", QString::number(m_currentSuite.totalTests));
    writer.writeAttribute("failures", QString::number(m_currentSuite.failedTests));
    writer.writeAttribute("errors", "0");
    writer.writeAttribute("skipped", QString::number(m_currentSuite.skippedTests));
    writer.writeAttribute("time", QString::number(m_currentSuite.totalDurationMs / 1000.0));
    writer.writeAttribute("timestamp", m_currentSuite.startTime.toString(Qt::ISODate));
    
    // Write test cases
    for (const auto& result : m_testResults) {
        writeXmlTestCase(writer, result);
    }
    
    writer.writeEndElement(); // testsuite
    writer.writeEndDocument();
    
    QString filePath = getReportFilePath("xml");
    bool success = writeToFile(filePath, xmlContent);
    
    if (success) {
        reportGenerated("XML", filePath);
    }
    
    return success;
}

bool TestReportGenerator::generateMarkdownReport()
{
    QString markdown;
    
    markdown += generateMarkdownHeader();
    markdown += generateMarkdownSummary();
    markdown += generateMarkdownTestResults();
    markdown += generateMarkdownBenchmarkResults();
    
    QString filePath = getReportFilePath("md");
    bool success = writeToFile(filePath, markdown);
    
    if (success) {
        reportGenerated("Markdown", filePath);
    }
    
    return success;
}

bool TestReportGenerator::generateCsvReport()
{
    QString csvContent;
    QTextStream stream(&csvContent);
    
    // CSV header
    stream << "Test Name,Category,Status,Duration (ms),Timestamp,Error Message,Warnings\n";
    
    // Test results
    for (const auto& result : m_testResults) {
        stream << result.testName << ","
               << result.category << ","
               << (result.passed ? "PASSED" : "FAILED") << ","
               << result.durationMs << ","
               << result.timestamp.toString(Qt::ISODate) << ","
               << "\"" << result.errorMessage << "\","
               << "\"" << result.warnings.join("; ") << "\"\n";
    }
    
    QString filePath = getReportFilePath("csv");
    bool success = writeToFile(filePath, csvContent);
    
    if (success) {
        reportGenerated("CSV", filePath);
    }
    
    return success;
}

bool TestReportGenerator::generateAllReports()
{
    bool success = true;
    
    success &= generateJsonReport();
    success &= generateHtmlReport();
    success &= generateXmlReport();
    success &= generateMarkdownReport();
    success &= generateCsvReport();
    
    return success;
}

QJsonObject TestReportGenerator::analyzeTestResults()
{
    QJsonObject analysis;
    
    // Test statistics
    analysis["test_statistics"] = calculateTestStatistics();
    
    // Benchmark statistics
    analysis["benchmark_statistics"] = calculateBenchmarkStatistics();
    
    // Trend analysis
    analysis["trend_analysis"] = generateTrendAnalysis();
    
    // Regressions
    QStringList regressions = detectRegressions();
    QJsonArray regressionArray;
    for (const QString& regression : regressions) {
        regressionArray.append(regression);
    }
    analysis["regressions"] = regressionArray;
    
    // Performance regressions
    QStringList perfRegressions = detectPerformanceRegressions();
    QJsonArray perfRegressionArray;
    for (const QString& regression : perfRegressions) {
        perfRegressionArray.append(regression);
    }
    analysis["performance_regressions"] = perfRegressionArray;
    
    return analysis;
}

QJsonObject TestReportGenerator::compareWithBaseline(const QString& baselineFile)
{
    QJsonObject comparison;
    
    // Load baseline file
    QFile file(baselineFile);
    if (!file.open(QIODevice::ReadOnly)) {
        comparison["error"] = "Could not open baseline file";
        return comparison;
    }
    
    QJsonDocument baselineDoc = QJsonDocument::fromJson(file.readAll());
    QJsonObject baseline = baselineDoc.object();
    
    // Compare test results
    if (baseline.contains("test_results")) {
        QJsonArray baselineTests = baseline["test_results"].toArray();
        
        // Create map of baseline results
        QMap<QString, QJsonObject> baselineMap;
        for (const auto& value : baselineTests) {
            QJsonObject test = value.toObject();
            baselineMap[test["name"].toString()] = test;
        }
        
        // Compare with current results
        QJsonArray differences;
        for (const auto& result : m_testResults) {
            if (baselineMap.contains(result.testName)) {
                QJsonObject baselineTest = baselineMap[result.testName];
                
                // Check for status change
                bool baselinePassed = baselineTest["passed"].toBool();
                if (baselinePassed != result.passed) {
                    QJsonObject diff;
                    diff["test"] = result.testName;
                    diff["type"] = "status_change";
                    diff["from"] = baselinePassed ? "passed" : "failed";
                    diff["to"] = result.passed ? "passed" : "failed";
                    differences.append(diff);
                }
                
                // Check for performance regression
                qint64 baselineTime = baselineTest["duration_ms"].toVariant().toLongLong();
                if (result.durationMs > baselineTime * 1.2) { // 20% slower
                    QJsonObject diff;
                    diff["test"] = result.testName;
                    diff["type"] = "performance_regression";
                    diff["baseline_ms"] = baselineTime;
                    diff["current_ms"] = result.durationMs;
                    diff["regression_percent"] = ((result.durationMs - baselineTime) * 100.0) / baselineTime;
                    differences.append(diff);
                }
            }
        }
        
        comparison["differences"] = differences;
    }
    
    return comparison;
}

QStringList TestReportGenerator::detectRegressions()
{
    QStringList regressions;
    
    // Simple regression detection based on test failures
    for (const auto& result : m_testResults) {
        if (!result.passed) {
            regressions << QString("Test failed: %1 - %2").arg(result.testName, result.errorMessage);
        }
    }
    
    return regressions;
}

QStringList TestReportGenerator::detectPerformanceRegressions(double threshold)
{
    QStringList regressions;
    
    // Group tests by category and calculate average performance
    QMap<QString, QList<double>> categoryTimes;
    for (const auto& result : m_testResults) {
        categoryTimes[result.category].append(result.durationMs);
    }
    
    // Check for performance issues
    for (auto it = categoryTimes.begin(); it != categoryTimes.end(); ++it) {
        QString category = it.key();
        QList<double> times = it.value();
        
        if (times.size() > 1) {
            // Calculate average
            double sum = 0;
            for (double time : times) {
                sum += time;
            }
            double average = sum / times.size();
            
            // Check if any test is significantly slower than average
            for (double time : times) {
                if (time > average * (1 + threshold)) {
                    regressions << QString("Performance regression in %1: %2ms (avg: %3ms)")
                                   .arg(category).arg(time, 0, 'f', 2).arg(average, 0, 'f', 2);
                }
            }
        }
    }
    
    return regressions;
}

QString TestReportGenerator::generateSummary()
{
    QString summary;
    QTextStream stream(&summary);
    
    stream << "=== " << m_reportTitle << " ===\n\n";
    stream << "Generated: " << QDateTime::currentDateTime().toString() << "\n";
    stream << "Environment: " << m_environmentInfo["os"].toString() << "\n\n";
    
    stream << "Test Suite Summary:\n";
    stream << "  Total Tests: " << m_currentSuite.totalTests << "\n";
    stream << "  Passed: " << m_currentSuite.passedTests << "\n";
    stream << "  Failed: " << m_currentSuite.failedTests << "\n";
    stream << "  Success Rate: " << QString::number(m_currentSuite.successRate * 100, 'f', 1) << "%\n";
    stream << "  Duration: " << m_currentSuite.totalDurationMs << "ms\n\n";
    
    return summary;
}

QString TestReportGenerator::generatePerformanceChart()
{
    // This would generate a visual chart - for now return placeholder
    return "[Performance chart would be generated here]";
}

QString TestReportGenerator::generateTestCoverageReport()
{
    QString coverage;
    QTextStream stream(&coverage);
    
    stream << "=== Test Coverage Report ===\n\n";
    
    // Group tests by category
    QMap<QString, int> categoryCounts;
    QMap<QString, int> categoryPassed;
    
    for (const auto& result : m_testResults) {
        categoryCounts[result.category]++;
        if (result.passed) {
            categoryPassed[result.category]++;
        }
    }
    
    for (auto it = categoryCounts.begin(); it != categoryCounts.end(); ++it) {
        QString category = it.key();
        int total = it.value();
        int passed = categoryPassed[category];
        double coverage = (passed * 100.0) / total;
        
        stream << category << ": " << passed << "/" << total 
               << " (" << QString::number(coverage, 'f', 1) << "%)\n";
    }
    
    return coverage;
}

bool TestReportGenerator::exportResults(const QString& format, const QString& filename)
{
    QString fullPath = m_outputDirectory + "/" + filename;
    
    if (format.toLower() == "json") {
        return generateJsonReport() && QFile::rename(getReportFilePath("json"), fullPath);
    } else if (format.toLower() == "html") {
        return generateHtmlReport() && QFile::rename(getReportFilePath("html"), fullPath);
    } else if (format.toLower() == "xml") {
        return generateXmlReport() && QFile::rename(getReportFilePath("xml"), fullPath);
    } else if (format.toLower() == "markdown" || format.toLower() == "md") {
        return generateMarkdownReport() && QFile::rename(getReportFilePath("md"), fullPath);
    } else if (format.toLower() == "csv") {
        return generateCsvReport() && QFile::rename(getReportFilePath("csv"), fullPath);
    }
    
    return false;
}

// Private helper methods

QString TestReportGenerator::generateHtmlHeader()
{
    return QString("<h1>%1</h1><p>Generated: %2</p>")
           .arg(m_reportTitle)
           .arg(QDateTime::currentDateTime().toString());
}

QString TestReportGenerator::generateHtmlFooter()
{
    return QString("<footer><p>Generated by Glance Test Report Generator</p></footer>");
}

QString TestReportGenerator::generateHtmlSummary()
{
    QString html;
    QTextStream stream(&html);
    
    stream << "<div class=\"summary-grid\">";
    
    stream << "<div class=\"summary-card\">";
    stream << "<h3>Total Tests</h3>";
    stream << "<div class=\"value\">" << m_currentSuite.totalTests << "</div>";
    stream << "</div>";
    
    stream << "<div class=\"summary-card\">";
    stream << "<h3>Passed</h3>";
    stream << "<div class=\"value success\">" << m_currentSuite.passedTests << "</div>";
    stream << "</div>";
    
    stream << "<div class=\"summary-card\">";
    stream << "<h3>Failed</h3>";
    stream << "<div class=\"value failure\">" << m_currentSuite.failedTests << "</div>";
    stream << "</div>";
    
    stream << "<div class=\"summary-card\">";
    stream << "<h3>Success Rate</h3>";
    stream << "<div class=\"value\">" << QString::number(m_currentSuite.successRate * 100, 'f', 1) << "%</div>";
    stream << "</div>";
    
    stream << "<div class=\"summary-card\">";
    stream << "<h3>Duration</h3>";
    stream << "<div class=\"value\">" << m_currentSuite.totalDurationMs << "ms</div>";
    stream << "</div>";
    
    stream << "</div>";
    
    return html;
}

QString TestReportGenerator::generateHtmlTestResults()
{
    QString html;
    QTextStream stream(&html);
    
    stream << "<table class=\"test-table\" id=\"testResultsTable\">";
    stream << "<thead><tr>";
    stream << "<th onclick=\"sortTable('testResultsTable', 0)\">Test Name</th>";
    stream << "<th onclick=\"sortTable('testResultsTable', 1)\">Category</th>";
    stream << "<th onclick=\"sortTable('testResultsTable', 2)\">Status</th>";
    stream << "<th onclick=\"sortTable('testResultsTable', 3)\">Duration (ms)</th>";
    stream << "<th>Details</th>";
    stream << "</tr></thead><tbody>";
    
    for (const auto& result : m_testResults) {
        QString statusClass = result.passed ? "status-passed" : "status-failed";
        QString status = result.passed ? "PASSED" : "FAILED";
        
        stream << "<tr>";
        stream << "<td>" << result.testName << "</td>";
        stream << "<td>" << result.category << "</td>";
        stream << "<td class=\"" << statusClass << "\">" << status << "</td>";
        stream << "<td>" << result.durationMs << "</td>";
        stream << "<td><button onclick=\"toggleTestDetails('" << result.testName << "')\">Details</button></td>";
        stream << "</tr>";
        
        // Add details row (hidden by default)
        if (!result.errorMessage.isEmpty() || !result.warnings.isEmpty()) {
            stream << "<tr id=\"details-" << result.testName << "\" style=\"display:none;\">";
            stream << "<td colspan=\"5\">";
            
            if (!result.errorMessage.isEmpty()) {
                stream << "<div class=\"error\">Error: " << result.errorMessage << "</div>";
            }
            
            if (!result.warnings.isEmpty()) {
                stream << "<div class=\"warnings\">Warnings: ";
                for (const QString& warning : result.warnings) {
                    stream << warning << "<br>";
                }
                stream << "</div>";
            }
            
            stream << "</td>";
            stream << "</tr>";
        }
    }
    
    stream << "</tbody></table>";
    
    return html;
}

QString TestReportGenerator::generateHtmlBenchmarkResults()
{
    QString html;
    QTextStream stream(&html);
    
    stream << "<table class=\"benchmark-table\">";
    stream << "<thead><tr>";
    stream << "<th>Benchmark</th>";
    stream << "<th>Value</th>";
    stream << "<th>Unit</th>";
    stream << "<th>Category</th>";
    stream << "</tr></thead><tbody>";
    
    for (const auto& result : m_benchmarkResults) {
        stream << "<tr>";
        stream << "<td>" << result.testName << "</td>";
        stream << "<td>" << result.value << "</td>";
        stream << "<td>" << result.unit << "</td>";
        stream << "<td>" << result.category << "</td>";
        stream << "</tr>";
    }
    
    stream << "</tbody></table>";
    
    return html;
}

QString TestReportGenerator::generateHtmlCharts()
{
    QString html;
    QTextStream stream(&html);
    
    stream << "<div class=\"chart-container\">";
    stream << "<canvas id=\"testResultsChart\"></canvas>";
    stream << "</div>";
    
    stream << "<div class=\"chart-container\">";
    stream << "<canvas id=\"performanceChart\"></canvas>";
    stream << "</div>";
    
    if (!m_benchmarkResults.isEmpty()) {
        stream << "<div class=\"chart-container\">";
        stream << "<canvas id=\"benchmarkChart\"></canvas>";
        stream << "</div>";
    }
    
    return html;
}

QString TestReportGenerator::generateMarkdownHeader()
{
    return QString("# %1\n\n**Generated:** %2\n\n**Environment:** %3\n\n")
           .arg(m_reportTitle)
           .arg(QDateTime::currentDateTime().toString())
           .arg(m_environmentInfo["os"].toString());
}

QString TestReportGenerator::generateMarkdownSummary()
{
    QString summary;
    QTextStream stream(&summary);
    
    stream << "## Summary\n\n";
    stream << "| Metric | Value |\n";
    stream << "|--------|-------|\n";
    stream << "| Total Tests | " << m_currentSuite.totalTests << " |\n";
    stream << "| Passed | " << m_currentSuite.passedTests << " |\n";
    stream << "| Failed | " << m_currentSuite.failedTests << " |\n";
    stream << "| Success Rate | " << QString::number(m_currentSuite.successRate * 100, 'f', 1) << "% |\n";
    stream << "| Duration | " << m_currentSuite.totalDurationMs << "ms |\n\n";
    
    return summary;
}

QString TestReportGenerator::generateMarkdownTestResults()
{
    QString markdown;
    QTextStream stream(&markdown);
    
    stream << "## Test Results\n\n";
    stream << "| Test Name | Category | Status | Duration (ms) |\n";
    stream << "|------------|----------|--------|---------------|\n";
    
    for (const auto& result : m_testResults) {
        QString status = result.passed ? "✅ PASSED" : "❌ FAILED";
        stream << "| " << result.testName 
               << " | " << result.category 
               << " | " << status 
               << " | " << result.durationMs << " |\n";
        
        if (!result.errorMessage.isEmpty()) {
            stream << "| *Error: " << result.errorMessage << "* | | | |\n";
        }
    }
    
    stream << "\n";
    
    return markdown;
}

QString TestReportGenerator::generateMarkdownBenchmarkResults()
{
    QString markdown;
    QTextStream stream(&markdown);
    
    if (!m_benchmarkResults.isEmpty()) {
        stream << "## Benchmark Results\n\n";
        stream << "| Benchmark | Value | Unit | Category |\n";
        stream << "|-----------|-------|------|----------|\n";
        
        for (const auto& result : m_benchmarkResults) {
            stream << "| " << result.testName 
                   << " | " << result.value 
                   << " | " << result.unit 
                   << " | " << result.category << " |\n";
        }
        
        stream << "\n";
    }
    
    return markdown;
}

void TestReportGenerator::writeXmlTestSuite(QXmlStreamWriter& writer)
{
    writer.writeStartElement("testsuite");
    writer.writeAttribute("name", m_currentSuite.suiteName);
    writer.writeAttribute("tests", QString::number(m_currentSuite.totalTests));
    writer.writeAttribute("failures", QString::number(m_currentSuite.failedTests));
    writer.writeAttribute("errors", "0");
    writer.writeAttribute("skipped", QString::number(m_currentSuite.skippedTests));
    writer.writeAttribute("time", QString::number(m_currentSuite.totalDurationMs / 1000.0));
    writer.writeAttribute("timestamp", m_currentSuite.startTime.toString(Qt::ISODate));
}

void TestReportGenerator::writeXmlTestCase(QXmlStreamWriter& writer, const TestResult& result)
{
    writer.writeStartElement("testcase");
    writer.writeAttribute("name", result.testName);
    writer.writeAttribute("classname", result.category);
    writer.writeAttribute("time", QString::number(result.durationMs / 1000.0));
    
    if (!result.passed) {
        writer.writeStartElement("failure");
        writer.writeAttribute("message", result.errorMessage);
        writer.writeCharacters(result.errorMessage);
        writer.writeEndElement(); // failure
    }
    
    writer.writeEndElement(); // testcase
}

void TestReportGenerator::writeXmlBenchmark(QXmlStreamWriter& writer, const TestBenchmarkResult& result)
{
    writer.writeStartElement("benchmark");
    writer.writeAttribute("name", result.testName);
    writer.writeAttribute("value", QString::number(result.value));
    writer.writeAttribute("unit", result.unit);
    writer.writeAttribute("category", result.category);
    writer.writeEndElement(); // benchmark
}

double TestReportGenerator::calculateSuccessRate()
{
    if (m_currentSuite.totalTests == 0) return 0.0;
    return (double)m_currentSuite.passedTests / m_currentSuite.totalTests;
}

QJsonObject TestReportGenerator::calculateTestStatistics()
{
    QJsonObject stats;
    
    stats["total_tests"] = m_currentSuite.totalTests;
    stats["passed_tests"] = m_currentSuite.passedTests;
    stats["failed_tests"] = m_currentSuite.failedTests;
    stats["success_rate"] = m_currentSuite.successRate;
    
    // Calculate average duration
    if (!m_testResults.isEmpty()) {
        qint64 totalDuration = 0;
        for (const auto& result : m_testResults) {
            totalDuration += result.durationMs;
        }
        stats["average_duration_ms"] = (double)totalDuration / m_testResults.size();
    }
    
    return stats;
}

QJsonObject TestReportGenerator::calculateBenchmarkStatistics()
{
    QJsonObject stats;
    
    if (!m_benchmarkResults.isEmpty()) {
        // Group benchmarks by category
        QMap<QString, QList<double>> categoryValues;
        
        for (const auto& result : m_benchmarkResults) {
            categoryValues[result.category].append(result.value);
        }
        
        QJsonObject categoryStats;
        for (auto it = categoryValues.begin(); it != categoryValues.end(); ++it) {
            QString category = it.key();
            QList<double> values = it.value();
            
            double sum = 0;
            for (double value : values) {
                sum += value;
            }
            
            QJsonObject catStats;
            catStats["count"] = values.size();
            catStats["average"] = sum / values.size();
            
            // Find min and max
            double min = values.first();
            double max = values.first();
            for (double value : values) {
                if (value < min) min = value;
                if (value > max) max = value;
            }
            catStats["min"] = min;
            catStats["max"] = max;
            
            categoryStats[category] = catStats;
        }
        
        stats["categories"] = categoryStats;
    }
    
    return stats;
}

QJsonObject TestReportGenerator::generateTrendAnalysis()
{
    QJsonObject trend;
    
    // Simple trend analysis based on test execution order
    if (m_testResults.size() > 1) {
        QList<double> durations;
        for (const auto& result : m_testResults) {
            durations.append(result.durationMs);
        }
        
        // Calculate trend (simple linear regression slope)
        double n = durations.size();
        double sumX = 0, sumY = 0, sumXY = 0, sumX2 = 0;
        
        for (int i = 0; i < durations.size(); ++i) {
            sumX += i;
            sumY += durations[i];
            sumXY += i * durations[i];
            sumX2 += i * i;
        }
        
        double slope = (n * sumXY - sumX * sumY) / (n * sumX2 - sumX * sumX);
        
        trend["performance_trend"] = slope;
        trend["trend_direction"] = slope > 0 ? "degrading" : (slope < 0 ? "improving" : "stable");
    }
    
    return trend;
}

QString TestReportGenerator::generatePerformanceTrendChart()
{
    return "[Performance trend chart]";
}

QString TestReportGenerator::generateTestResultPieChart()
{
    return "[Test result pie chart]";
}

QString TestReportGenerator::generateTimelineChart()
{
    return "[Timeline chart]";
}

bool TestReportGenerator::writeToFile(const QString& filename, const QString& content)
{
    QFile file(filename);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        qDebug() << "Could not open file for writing:" << filename;
        return false;
    }
    
    QTextStream out(&file);
    out << content;
    file.close();
    
    return true;
}

QString TestReportGenerator::getReportFilePath(const QString& extension)
{
    QString timestamp = QDateTime::currentDateTime().toString("yyyyMMdd_hhmmss");
    return m_outputDirectory + "/" + "GlanceTestReport_" + timestamp + "." + extension;
}

QString TestReportGenerator::generateHtmlAnalysis()
{
    QString html;
    QTextStream stream(&html);
    
    QJsonObject analysis = calculateTestStatistics();
    
    stream << "<div class=\"analysis-section\">";
    stream << "<h3>Test Analysis</h3>";
    
    // Show basic statistics
    stream << "<div class=\"analysis-stats\">";
    stream << "<p>Success Rate: " << QString::number(calculateSuccessRate() * 100, 'f', 1) << "%</p>";
    stream << "</div>";
    
    stream << "</div>";
    return html;
}

} // namespace Glance::Testing
